version: '3'
services:
  raft1:
    build: .
    ports:
      - "5001:5001"
    networks:
        - raft-cluster
    command: redis-server --port 5001 --dbfilename raft.rdb --protected-mode no --loadmodule /data/redisraft.so raft-log-filename raftlog.db addr raft1:5001
  raft2:
    build: .
    ports:
      - "5002:5002"
    networks:
        - raft-cluster
    command: redis-server --port 5002 --dbfilename raft.rdb --protected-mode no --loadmodule /data/redisraft.so raft-log-filename raftlog.db addr raft2:5002
    depends_on:
      - raft1
  raft3:
    build: .
    ports:
      - "5003:5003"
    networks:
        - raft-cluster
    command: redis-server --port 5003 --dbfilename raft.rdb --protected-mode no --loadmodule /data/redisraft.so raft-log-filename raftlog.db addr raft3:5003
    depends_on:
      - raft1
  client:
    build: .
    networks:
        - raft-cluster
    command: tail -f /dev/null
    depends_on:
      - raft1
      - raft2
      - raft3
    volumes:
      - ./output:/output
      - ./:/app
  benchmark:
    image: redislabs/memtier_benchmark:latest
    networks:
        - raft-cluster
    entrypoint: /usr/bin/tail
    command: -f /dev/null
    depends_on:
      - raft1
      - raft2
      - raft3
    volumes:
      - ./output:/output
      - ./:/app
networks:
    raft-cluster: