version: '3'
services:
  raft1:
    build: .
    ports:
      - "5001:5001"
    networks:
        - raft-cluster
    cgroup_parent: raft1
    command: redis-server --port 5001 --dbfilename raft.rdb --protected-mode no --loadmodule /data/redisraft.so raft-log-filename raftlog.db addr 0.0.0.0:5001
  raft2:
    build: .
    ports:
      - "5002:5002"
    networks:
        - raft-cluster
    cgroup_parent: raft2
    command: redis-server --port 5002 --dbfilename raft.rdb --protected-mode no --loadmodule /data/redisraft.so raft-log-filename raftlog.db addr 0.0.0.0:5002
    depends_on:
      - raft1
  raft3:
    build: .
    ports:
      - "5003:5003"
    networks:
        - raft-cluster
    cgroup_parent: raft3
    command: redis-server --port 5003 --dbfilename raft.rdb --protected-mode no --loadmodule /data/redisraft.so raft-log-filename raftlog.db addr 0.0.0.0:5003
    depends_on:
      - raft1
  client:
    build: .
    networks:
        - raft-cluster
    cgroup_parent: raft3
    command: python3 /app/main.py
    depends_on:
      - raft1
      - raft2
      - raft3
    volumes:
      - ./output:/output
      - ./:/app
networks:
    raft-cluster: